### ISSUE TITLE
Current Status Error

### ISSUE THREAD

**Issue by Owlbin** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#47]
"Something has changed with Twitch. Please report this to the RuneLite plugin maintainer. The time of this message was 04:04:58. An error occurred with code: 400"

**Comment by pepijnverburg** [comment]
Hi @Owlbin, thanks for opening this issue! 

Couple of questions:
- Did you receive additional error details in the your chat box? 
- Does it happen all the time? Or does the plugin + extension work and shows live info in Twitch and only sometimes you receive this message?

**Comment by Owlbin** [comment]
It doesn't look like I am getting any extra errors.

Since installing the plugin I have always gotten this current status error and it hasn't worked yet.

**Comment by pepijnverburg** [comment]
Hi @Owlbin, just saw that I missed your reply on this issue. Did you manage to get it work? One way I would recommend troubleshooting it is to reset the plugin settings (some users have been filling in the Twitch Extension Token into the Twitch Client ID accidentally, this causes 400 errors). After the reset you should then re-enter the copied Twitch Extension Token from the extension configuration page on the twitch website.

**Comment by pepijnverburg** [comment]
Closed due to inactivity.
